version: '3.3'
services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
